### ISSUE TITLE
A way to exclusively sort type-only imports

### ISSUE THREAD

**Issue by DaveLo** [IanVS/prettier-plugin-sort-imports#107]
**Is your feature request related to a problem?**
I'm not sure if this is a bug or feature tbh, but if I have `<TYPES>` in the importOrder array my merged imports get split, which shouldn't happen in the version of TS I'm using (5.1.3) and makes the import lines more verbose. 

I'm using prettier v2.8.8 and v4.0.2 of this lib.

**Describe the solution you'd like**
It would be ideal if there was a way to exclusively sort type-only imports that wouldn't affect mixed imports.

**Describe alternatives you've considered**
My current options seem to be either have type-only imports mixed into normal imports by the sorter, or have type imports always on a separate line even if there is an existing import statement.

**Additional context**
Config:
```json
{
  "importOrder": [
      "",
      "^@myorg/(.*)$",
      "",
      "^[./]",
      "",
      "<TYPES>"
  ],
  "importOrderTypescriptVersion": "5.1.3"
}
```
Simple Example: 
```typescript
// before
import { dbMiddleware, type DBKeys } from "@myorg/db";
import type { GetCustomerReq } from "@myorg/schema";

// after
import { dbMiddleware } from "@myorg/db";

import type { DBKeys } from "@myorg/db";
import type { GetCustomerReq } from "@myorg/schema";

// expected
import { dbMiddleware, type DBKeys } from "@myorg/db";

import type { GetCustomerReq } from "@myorg/schema";
```

**Comment by IanVS** [comment]
Thanks for bringing this up.  I could see maybe adding a special word for `<TYPE_ONLY>` or something like that.  I am about to go on vacation for a while, but feel free to submit a PR if you'd like to dig in, and I can take a look when I get back (or @fbartho may be able to while I'm gone).

**Comment by fbartho** [comment]
@DaveLo I see why you're frustrated by this.

The whole point of the `<TYPES>` feature was _"all type imports should be in one place, because you know they cannot then have side-effects"_ -- so it's working as we intended it to (to be clear, I don't want this in my codebases, but I was convinced that others do!)

As @IanVS says, we could build a thing that works like you ask -- and we can collectively bike-shed how to spell it. If you want to submit a PR, I'd be happy to provide feedback and help you get it functioning, and then when @IanVS comes back, we can discuss about getting it merged & released.

**Comment by DaveLo** [comment]
I can take a crack at it!

**Comment by fbartho** [comment]
@DaveLo I'd like to encourage you to weigh whether your requested feature is worth the additional *special word* -- as this is likely to be pretty complex code to weave into the rest of the plugin, and will likely have a bunch of nuance that needs to be documented.

Specific problem cases that jump to mind include:
- What happens if both `<TYPES>` and `<TYPES_ONLY>` are present?
- `<TYPES>` supports a trailing regex, so you sort only the types that match a pattern. Would `<TYPES_ONLY>` also have this?
- What happens when a user originally has something as a `<TYPES_ONLY>` import, and then later on imports one runtime dependency? -- Would the import suddenly move away from the `<TYPES_ONLY>` section into another section? (I think users would be confused)

**Comment by DaveLo** [comment]
@fbartho I was thinking about that while reading through the codebase over the weekend. I almost think it more belongs as an option? I know you all have been working to limit down option complexity though.

To me it seems we would either want types to separate (current behavior) or only to separate type-only imports (proposed option). Making it something to opt-in on makes it easier to document the behavior while removing some of those edge cases.

Does that seem reasonable?

**Comment by DaveLo** [comment]
I generally think that idea would be intriguing and allow a user to opt in to the level of complexity they need.

I don't think it meets my use case from a style perspective (explicit order based on type-only without affecting mixed order). That said, I'm also now pretty convinced that what I'm looking for is outside the scope of what this plugin is aiming for as it's a pretty niche use case and probably not worth the added complexity of either a new reserved keyword or flag.
