### ISSUE TITLE
importOrderSeparation

### ISSUE THREAD

**Issue by SalahAdDin** [IanVS/prettier-plugin-sort-imports#117]
**Is your feature request related to a problem?**
In the original library, it was easy to get blank lines between import groups, but in this one, you have to add blank lines to the import groups array which is unesthetic and less intuitive.

**Describe the solution you'd like**
The **Trivago** library does include a setting that adds blank lines between import groups by default, and it makes easier and more intuitive the configuration.

>  importOrderSeparation
> type: boolean
> default value: false
> A boolean value to enable or disable the new line separation between sorted import declarations group. The separation takes place according to the importOrder.
> "importOrderSeparation": true,

It would be nice to have this setting back to this new library.

**Describe alternatives you've considered**
I'm thinking of coming back to the old library since the blank lines setting is very useful and from all features introduced by this library, I don't use anyone.

**Additional context**

**Comment by IanVS** [comment]
Hi there @SalahAdDin, thanks for the suggestion.  The trivago version does not support custom blank lines like this one does, which is why it needs to have `importOrderSeparation`.  Our approach here is to try to make `importOrder` as flexible as possible, so that it's not necessary to have a bunch of extra options that you have to learn and configure.  After all, prettier itself only has a handful of configuration options.  

So, it's entirely possible to achieve what you want, by adding blank groups (like `""`) to your `importOrder` between your other items.  That is the best way to achieve the previous `importOrderSeparation`.  If you share your config, I can give an example of what it would look like.

**Comment by fbartho** [comment]
I concur with @IanVS. We’re more flexible than trivago in this case, while having fewer options, but I’m sorry if that breaking change doesn’t match your preference.
