### ISSUE TITLE
Known issues? Looking for more maintainers?

### ISSUE THREAD

**Issue by fbartho** [IanVS/prettier-plugin-sort-imports#13]
At the top of the readme you mention this is a best-effort fork of the `trivago/prettier-plugin-sort-imports` but that it may not stay up-to-date forever.

I've been hesitant to use `trivago/...` because of all of the breaking issues, but it seems like on each issue I've examined that I would consider a dealbreaker I find a comment from @IanVS saying that this fork fixes that problem :D

So I guess my questions are:
- [ ] are there any known issues from `trivago/...` that still need to be fixed in this fork, or that you would consider danger for somebody trying to apply this plugin to a large codebase?
- [ ] are there any lurking / big issues that need to be fixed sooner rather than later? (TypeScript/babel upgrades?)
- [ ] are you looking for regular/casual collaborators? or is your hope to merge this fork back into the upstream?

**Comment by fbartho** [comment]
And to be clear: if you're primarily looking to make forward progress with this fork, and were looking for more casual collaborators I would put my hat in the ring. -- If you'd rather not have a lot of primary development in this fork, then that's fine too -- I wouldn't want to push you beyond your vision here.

I'm currently a regular OSS collaborator on GitHub.com/danger/danger-js and few other projects.

**Comment by IanVS** [comment]
Hi @fbartho thanks for dropping by!  

Originally my plan was to only include @blutorange's work to avoid sorting side-effect imports, because I saw that as a critical bugfix that the maintainers of the trivago project disagreed with.  

Then @blutorange and I made some other fixes, and I found some nice PRs from the upstream project that seemed stalled out that I brought over.  And, well, instead of needing to worry about staying up-to-date with upstream, we've ended up diverging.  I think this is fine.  I'd like to continue being able to pull in changes (either proposed or merged) from upstream when possible, but merging this back into the Trivago is a non-goal.  

>are there any known issues from trivago/... that still need to be fixed in this fork, or that you would consider danger for somebody trying to apply this plugin to a large codebase?

I don't know of any issues that remain in this project that are dangerous, and I believe it to be safe to apply to a large project.  I use it in production at work, without problems.

> are there any lurking / big issues that need to be fixed sooner rather than later? (TypeScript/babel upgrades?)

I can't think of anything, but maybe @blutorange has something in mind?

> are you looking for regular/casual collaborators?

Sure!  I'd be happy for the help.  Immediate tasks that come to mind would be reviewing https://github.com/IanVS/prettier-plugin-sort-imports/pull/12, fixing https://github.com/IanVS/prettier-plugin-sort-imports/issues/9 (minor annoyance), or going through the issues / PRs in the trivago repo to see if there are any that we could consider fixing here.  Or, if you have other thoughts on improvements that could be made, feel free to open an issue and we can discuss.

Cheers!

**Comment by IanVS** [comment]
Oh, and if you'd like to submit a PR to update the wording in the README, I'd be open to that as well.  It's not exactly accurate anymore as you pointed out.

**Comment by blutorange** [comment]
> are there any known issues from trivago/... that still need to be fixed in this fork, or that you would consider danger for somebody trying to apply this plugin to a large codebase?

Since this is "just" a linter, I'd consider any possible risk as rather low. Said that, this https://github.com/trivago/prettier-plugin-sort-imports/issues/116 is something we should check whether that issue still exists and fix it, non-deterministic ordering may result in different formatting depending on the build environment.

> are you looking for regular/casual collaborators

Yes, as IanVS said, any help is welcome.

> but merging this back into the Trivago is a non-goal

Personally I wouldn't mind if they wanted to merge this back, but that doesn't seem too likely at this point.
