### ISSUE TITLE
Separate type imports only if necessary.

### ISSUE THREAD

**Issue by curiosbasant** [IanVS/prettier-plugin-sort-imports#185]
**Is your feature request related to a problem?**
I like to have my imports on a single line, but importing types quickly makes it span in multiple lines.
So I would like to have a way, to separate out the type imports on a separate line below when the import statements exceed the prettier `printWidth` limit.

**Describe the solution you'd like**
For example,
```ts
// before
import {
  applyPatches,
  enablePatches,
  produce,
  produceWithPatches,
  type Draft,
  type Objectish,
  type Patch,
} from 'immer'

// after
import { applyPatches, produce, produceWithPatches, enablePatches } from 'immer'
import type { Draft, Objectish, Patch } from 'immer'
```

**Additional context**
But if possible, the imports and type imports should be kept together if it could fit in a single line.
For example, the following should be unchanged.
```ts
import { applyPatches, produce, type Draft, type Patch } from 'immer'
```

**Comment by fbartho** [comment]
If you want to *always* split your type imports into a different import expression, you can do that with the `<TYPES>` magic word: https://github.com/IanVS/prettier-plugin-sort-imports?tab=readme-ov-file#4-group-type-imports-separately-from-values

We do not have the ability to dynamically make that decision if-and-only-if the line would otherwise wrap, sorry!

**Comment by curiosbasant** [comment]
Yes, I was aware of the `<TYPES>` thing. 
But how could I make it so that the type imports automatically always appear at the bottom of import expressions?
Thanks!

**Comment by fbartho** [comment]
I’ve never seen a codebase organized like that! In this situation, especially if you’re just curious (😉) about it, I would recommend forking this package to implement that feature.

The goal of this package is to implement a mostly opinionated set of additions on top of prettier, and there’s no reason you can’t layer your own style on top of this. Good luck!

**Comment by IanVS** [comment]
I think this request is similar to https://github.com/IanVS/prettier-plugin-sort-imports/issues/147#issuecomment-2378281985.  

I think it would be difficult to build this in a way that considers line-length limits (due to the way that prettier works), and while we _could_ add an option to break apart type and value imports while keeping them next to each other, one of our goals is to keep our number of options to a minimum.  If you would like to _always_ split apart type and value imports, while keeping those lines next to each other, please open a new feature request and we can use that to gauge interest on whether the behavior should perhaps be changed in a future major version.  Though I have to admit I think it will be a tough sell.
