### ISSUE TITLE
enable imports without naming to be sorted

### ISSUE THREAD

**Issue by m-kolomoyets** [IanVS/prettier-plugin-sort-imports#186]
Currently plugin works for imports that are named like this:
- Default 
```ts
import Module from '...'
```

- Named 
```ts
import { Module } from '...'
```

- With asterisks
```ts
import * as Module from '...'
```

BUT:
The imports without naming like this:
```ts
import "@/styles/index.css"
```
is ignored even writing such rules from documentation:
```json
[

 "^(@/styles)(/*)$",
 "^(?!.*[.]css$)[./].*$",
 ".css$"
]
```

## Describe the solution you'd like
Maybe makes sense to configure that imports may not have namings, but being imported directly in file, like global styles where no need to name it and apply somewhere

Thanks in advance!)

**Comment by IanVS** [comment]
@m-kolomoyets these are called "side-effect imports" because they do not import any code from the module being imported, and therefore are only used to trigger side-effects.  In general, the order of these side-effects can matter a lot.  For instance, if you import two css files, the order you import them can change the order in the final css cascade, and therefore change the styling of your site.  For this reason, we do not sort files that nothing is being imported from.

**Comment by m-kolomoyets** [comment]
Thanks for the message. It totally makes sense this way.
