### ISSUE TITLE
Feature: Smarter auto-detection of parser-plugins

### ISSUE THREAD

**Issue by fbartho** [IanVS/prettier-plugin-sort-imports#24]
**Is your feature request related to a problem?**
It'd be great if users didn't have to configure `importOrderParserPlugins` (default: `"auto-detect"`)

**Describe the solution you'd like**
For certain common cases we should be able to guess which parser plugins are needed.

Heuristics:
1. Detect if typescript is installed in node_modules and infer `typescript` is a needed parser plugin
1. Detect if tsconfig is present in the nearest directory to package.json and infer `typescript`
1. Detect if tsconfig includes the experimentalDecorators option (should that infer decorators-legacy or decorators new?)
1. How can we detect if `jsx` is necessary?

**Describe alternatives you've considered**
Continue the status quo of requiring parser plugins to be configured if your code is not pure classic JS

**Comment by IanVS** [comment]
>Detect if typescript is installed in node_modules and infer typescript is a needed parser plugin

This is tricky, I've used a heuristic like this in another project, and ran into problems with someone who had typescript installed due to some other dependency, but wasn't actually using it.  I think it's a little safer to check for `typescript` in the actual `package.json`, but then again, it can be hard to find the right `package.json` in a monorepo setup.

Detecting jsx is tricky unless files are named with `.jsx`.  

I'm tempted to continue with status-quo, unless we hear that it's causing confusion.  With fewer options in the next major release, hopefully the docs will be easier to read and understand, which might also help.

**Comment by fbartho** [comment]
Removed this ticket from the 4.0 milestone, still want to do it, but not blocking the breaking release

**Comment by IanVS** [comment]
I'd like to take a crack at solving parser plugins in 4.0.  I don't know about auto-detecting, but maybe we can be a bit smarter about which plugins to include by default depending on the file extension.  We should not include `jsx` for `.vue` files, for instance, and should only include `typescript` for `.ts` and `.tsx` files.

**Comment by fbartho** [comment]
I don’t think we can or should worry about auto-detecting Flow either (not sure if we needed to do so)

**Comment by IanVS** [comment]
Plugins are better now after https://github.com/IanVS/prettier-plugin-sort-imports/pull/91.  Going to consider this "done" for now, though we may revisit it again in the future.
