### ISSUE TITLE
Feature: group type-imports when sorting Identifiers

### ISSUE THREAD

**Issue by fbartho** [IanVS/prettier-plugin-sort-imports#25]
**Is your feature request related to a problem?**
In #20 we're offering an option to migrate `import type {` expressions into value-imports when needed `import {type
In #22 we're discussing deleting that configuration-flag, and instead having an opinionated default.

We realized that we probably want to have some configuration for deciding which mode we want.

Example:

```typescript
import type {A} from 'a';
import {B} from 'a';
import type {C} from 'a';
import {D} from 'a';
```

Desired Flavors:
1. #19 (without #20) would produce
```typescript
import type { A, C } from 'a';
import { B, D } from 'a';
```
2. #19 with #20 would produce
```typescript
import  { type A, B, type C, D } from 'a';
```
3. Not available yet:
```typescript
import  { type A, type C, B, D } from 'a';
```
4. Not available yet: (witnessed in @IanVS's codemod)
```typescript
import  { B, D, type A, type C } from 'a';
```

**Describe the solution you'd like**

1. "don't merge any imports" should be spelled `importOrderMergeTypeImports: "disable"`
2. in #22 we offered that _Desired Flavor 1_ could be spelled as `importOrderMergeTypeImports: "separate"`
3. in #22 we offered that _Desired Flavor 2_ could be spelled as `importOrderMergeTypeImports: "mixed"`
4. we could spell _Desired Flavor 3_ as `importOrderMergeTypeImports: "mixed-first"`
5. we could spell _Desired Flavor 4_ as `importOrderMergeTypeImports: "mixed-last"`

**Describe alternatives you've considered**

- Pick a specific default, and don't offer any options
- For sub feature `"mixed"` maybe mixed should actually just refer to one of the options, and not offer the others.

## Open concerns

- [ ] Should this option be spelled `importOrderMergeImports` instead?
- [ ] Should `"separate"` aggressively unmerge any `type` imports in a value expression into 2 import statements `import type + import {}` expressions?
- [ ] What should the default be?

**Comment by fbartho** [comment]
I vote the default value should be `"mixed-first"` or `"mixed-last"` ahead of the other options.

**Comment by fbartho** [comment]
I forgot to propose the option of "group all the `import type` expressions at the top" -- it's not one I want, but I can update the discussion if we want that.

**Comment by IanVS** [comment]
How that it's possible to combine type and value imports (`importOrderCombineTypeAndValueImports`) and to place type imports where desired (https://github.com/IanVS/prettier-plugin-sort-imports/pull/44), I think the only thing that's missing from this request is to control the order of mixed type and value imports.  I made the call to always put types last as part of `importordersortspecifiers`, and I don't think it's important enough of a style difference to add an option just to control it, when we're trying to cut down on our current options.

So, with that said, I think that main request in this issue is done now, right?  Can we close it, or is there still more to do?

**Comment by fbartho** [comment]
I think you've made the necessary decision, right?

**Comment by IanVS** [comment]
Let's run with this for now, and if we hear an outcry from users we can find a way to adjust in the future.  Thanks!
