### ISSUE TITLE
Maintenance: Drop Lodash

### ISSUE THREAD

**Issue by fbartho** [IanVS/prettier-plugin-sort-imports#26]
Lodash is a big, regularly updating dep. We only use 2 modules from it, and it #21 we discussed dropping lodash for other techniques.

**Describe the solution you'd like**
Replace `lodash.clone` and `lodash.isequal` with simple JS-built-in options such as `structuredClone` or `JSON.parse(JSON.stringify` and `Object.isEqual`

**Describe alternatives you've considered**
Leave lodash alone :leave-britney-gif:

**Comment by mpcsh** [comment]
Hey, I was bored so I took a stab at this. My $0.02 is you should leave lodash alone — here's why:
* `lodash.isEqual` is too useful and too annoying to replicate. `Object.isEqual` isn't a thing, much as I wish :lolsob:
* `lodash.clone` seems to preserve type information whereas `structuredClone` / `JSON.parse(JSON.stringify)` don't. For example, consider [the map predicate in this line](https://github.com/IanVS/prettier-plugin-sort-imports/blob/3233783693f05c0c9407d76b0d1c076e50276080/src/utils/adjust-comments-on-sorted-nodes.ts#L20):
  * If you try to refactor it to just be `structuredClone` by reference, you get a type error on `structuredClone`'s second parameter (an options bag), because `map` predicates are supposed to take the element index as the second parameter.
  * If you then try to refactor it to be `(node) => structureClone(node)` to get around that type error, the `finalNodesClone` array gets typed as `any`, whereas `lodash.clone` correctly types it as `ImportOrLine[]`. This doesn't yield any errors (unless you use [`noImplicitAny`](https://www.typescriptlang.org/tsconfig#noImplicitAny)), but it _does_ introduce implicit `any`s, which can cause TypeScript to unexpectedly let you down.

**Comment by jasikpark** [comment]
possibly useful repo: https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore

**Comment by jasikpark** [comment]
https://github.com/angus-c/just 👀

**Comment by ArnaudBarre** [comment]
structuredClone is too young anyway to be used in a wide project, but in 1/2 years I think the the default node types would be improved to keep type information. Or it could be wrap in a one liner like: `const clone = <T>(value: T): T => structureClone(value)`. Using a runtime lib just for a bad default types is not ideal IMO.

**Comment by IanVS** [comment]
I'm inclined to keep what we have for now, since:

1) Lodash is battle tested, and it's been working fine for us so far as far as I know.
2) It has good typescript support
3) It sounds like there are not great native solutions just yet.

Happy to reconsider, but using two small functions from lodash seems fine in my opinion.
