### ISSUE TITLE
Special word for "side-effect only" imports

### ISSUE THREAD

**Issue by aleclarson** [IanVS/prettier-plugin-sort-imports#51]
**Is your feature request related to a problem?**
I'm sick of manually moving "automatic imports" (inserted by VS Code) above the imports that are dedicated to side effects (eg: `import` without `from` keyword).

```ts
import React from 'react'
import './foo.css'
import Blah from 'blah' // VS Code inserted this line. 🤦 
```

**Describe the solution you'd like**
Add a `<SIDE_EFFECT_MODULES>` special word for ordering purposes.

**Comment by IanVS** [comment]
I could see that being irritating, especially if you are using css imports this way.  

The original point of this fork was to avoid sorting side-effect imports, so I definitely would not want to sort between such imports themselves, but grouping where they appear might have its uses (e.g. as shown here, to ensure that the current module's css is imported _after_ any other components that are being imported.  

@blutorange what do you think about this proposal?

**Comment by fbartho** [comment]
From a generic perspective it’s dangerous to move side effect imports at all.

We could discuss a config-syntax to allow overriding that, but I don’t think it’s safe.

For imports that have no side effects it doesn’t matter if they come after side effect imports.

Have you considered importing your CSS files first? Then VSCode’s behavior wouldn’t cause problems for you. Unfortunately we can’t help change VSCode’s behavior, and encoding your rules might be unwise generally.

Each import group (eg. Your hypothetical `<SIDE EFFECTS>` group) is currently sorted internally, so that would be an additional complexity in your proposal.

**Comment by fbartho** [comment]
Additionally: any import *might have side effects* “side-effect-only import” are a heuristic that we use to communicate the developer intent, and balance the value of sorted imports with the inconvenience of side-effect constraints.

**Comment by jasikpark** [comment]
for example Astro components have styles tied to them on import

```
import MainLayout from "./MainLayout";
import BlueButton from "./BlueButton";
```

both have side effects. I've gone with adding a regex for all imports with a Layout in the name sorted to the top, maybe that can work for your setup? Is it just CSS files you are importing? I suppose "only side-effect" isn't something that can be detected with the regex tho

**Comment by aleclarson** [comment]
I tried targeting only `.css` files, but it seems the first matching regex takes precedence?
```diff
 {
   "importOrder": [
     "<TYPES>",
     "<THIRD_PARTY_MODULES>",
-    "^[./]"
+    "^[./]",
+    "[.]css$"
   ],
   "importOrderSortSpecifiers": true,
   "importOrderCaseInsensitive": true,
   "importOrderMergeDuplicateImports": true,
   "importOrderBuiltinModulesToTop": true,
   "plugins": ["@ianvs/prettier-plugin-sort-imports"]
 }
```

**Comment by IanVS** [comment]
Yeah, I use css modules, so they're not side-effect-only.   :(

I'm not sure I see a really safe way to do what you're asking for right now, though I'll keep thinking about it.  It would be nice if there were a way to make VSCode put auto-imports up at the top of all imports, instead of the bottom...

**Comment by aleclarson** [comment]
Could add an `importOrderForceBottom` array option:
```json
"importOrderForceBottom": [".css$"],
```
This would create a separate ordering group that always gets moved below imports not matching any of the specified patterns.

**Comment by fbartho** [comment]
Just for context: The next phase of (breaking) development for this project is to try to remove as many configuration flags as we can.

The current configuration flags lead to a lot of complexity, and edge cases, and lead to confusion — all of which make it difficult to maintain this project, and to document how to use it.

Ideally, we’d be able to simplify this down to *just* the `importOrder` matchers.

**Comment by fbartho** [comment]
I'm going to close this ticket as `"Not Planned"` for now. If we want to revisit that we can discuss reopening this ticket!

**Comment by vincerubinetti** [comment]
I really think deserves it's own flag. I've used this plugin for a long time, and I think it is perfect (simplicity, right level of granularity for options) except for this issue.

> We could discuss a config-syntax to allow overriding that, but I don’t think it’s safe.

This feels like a similar argument about React's `dangerouslySetInnerHTML` or eslint warnings about Vue's `v-html`. Yes, it is not guaranteed to be safe, but it is not guaranteed to be unsafe either. These imports should cause side-effects, yes. But it's not guaranteed that they'll negatively affect other imports.

Consider this case, which I believe is common because it's really the only time I ever have side-effect imports:

```ts
import SomeComponent from "@/components/Blah";
import "some-css-reset.css";
import "./our-global-styles.css";
```

Where the order of the side effect imports themselves matters, but their order within all the imports doesn't matter. In other words, keep the first sentence from the readme here, but allow disabling the second:

> To preserve potential side effects, these kind of side effect imports are classified as unsortable. They also behave as a barrier that other imports may not cross during the sort.

For my cases, having a `disableSideEffectBarrier` option would do the trick. (Then I guess `// prettier-ignore` could be used to opt back in on a per case basis.)

I understand the reasoning behind the decision not to have this, and having it could cause issues for someone (it definitely should be opt-in), but I just think the cases where it would be of great benefit are very common and the cases where it would cause an issue are pretty rare.

**Comment by IanVS** [comment]
So in your example, you want the css imports to be in the same order, but move the other import below them?

**Comment by IanVS** [comment]
Side note, I just saw that VS Code 1.84 has a note in their release notes:

```
Import grouping
Generated imports are now always put to the top of the file or below existing import blocks. This is supported for most common programming languages.
```

That "or" is a bit confusing to me.  It's like it's saying it'll always put imports at the top _or_ the bottom.  Did it put them in the middle before?  And how does it decide whether to put them at the top or the bottom?  I wish they would link to PRs from their release notes...

**Comment by vincerubinetti** [comment]
To clarify, in my case I don't need the CSS at the top. As you said I think the standard there is to put them at the bottom, and I tend to write my CSS in a way that is fine with that (CSS modules for components, classes that are global and less specific in side effect imports, etc.).

Not sure what the best answer is here. I appreciate the difficulty of trying to make a flexible yet simple and non-error prone API. I at least think it's worth further exploration, though, given how common a need it is.

**Comment by IanVS** [comment]
@vincerubinetti are you saying that if you had an option to put all side-effect imports at the end of your import blocks, without reordering multiple side-effect imports themselves, that would meet your needs?

**Comment by vincerubinetti** [comment]
Indeed, yeah. I know I'm biased but I feel like that's a pretty common need.

**Comment by Kamahl19** [comment]
I think there is a way this can be done safely. Keep the current behaviour as is including the current behaviour of side-effect imports **except** the .css imports. If there is a side-effect-free import under the .css import, move it above and let it sort with the rest side-effect-free imports.

**Comment by IanVS** [comment]
You can now use `importOrderSafeSideEffects` in release [v4.7.0](https://github.com/IanVS/prettier-plugin-sort-imports/releases/tag/v4.7.0) to specify side-effect imports that should be considered "safe" for sorting.
