### ISSUE TITLE
Import sorting doesn't work on certain import types

### ISSUE THREAD

**Issue by Xenfo** [IanVS/prettier-plugin-sort-imports#69]
**Your Environment**

-   **Prettier version**: 2.8.8
-   **node version**: 19.8.1
-   **package manager**: yarn@3
-   **IDE**: VScode

**Describe the bug**

The reproduction code isn't sorted properly. When the `import './global.css';` is at the top, it isn't sorted to bottom. When at the bottom, it's split with a newline like it should be.

**To Reproduce**

Sort using VSCode or Prettier CLI.

**Expected behavior**

It sorts properly.

**Screenshots, code sample, etc**

```js
import './globals.css';
import clsx from 'clsx';
import { Work_Sans as WorkSans } from 'next/font/google';
```

**Configuration File (cat .prettierrc, prettier.config.js, .prettier.js)**

```js
{
  "semi": true,
  "singleQuote": true,
  "bracketSpacing": true,
  "trailingComma": "none",
  "pluginSearchDirs": false,
  "importOrderTypeScriptVersion": "5.0.4",
  "importOrder": ["<THIRD_PARTY_MODULES>", "", "^@/(.*)$", "", "^[./]"],
  "plugins": [
    "@ianvs/prettier-plugin-sort-imports",
    "prettier-plugin-tailwindcss"
  ]
}
```

**Error log**

No logs.

**Contribute to @ianvs/prettier-plugin-sort-imports**

-   [ ] I'm willing to fix this bug 🥇

**Comment by IanVS** [comment]
Hi, this is expected behavior. Side effect imports (imports with only a specifier) are not safe to rearrange. If you had two css imports like that, and we sorted them, it could change the generated cascade and break the styles in your app. The trivago version of this plugin does sort these imports, so you can use that if you're not worried about potential issues.

**Comment by Xenfo** [comment]
Ah ok, thanks for the explanation.

**Comment by LordZardeck** [comment]
> Hi, this is expected behavior. Side effect imports (imports with only a specifier) are not safe to rearrange. If you had two css imports like that, and we sorted them, it could change the generated cascade and break the styles in your app. The trivago version of this plugin does sort these imports, so you can use that if you're not worried about potential issues.

I completely understand this, but I think it would be nice to be able to hard specify some side effect imports directly. For example, we have to include `import 'twin.macro'` in every file, and we'd like it to always be at the top, but if we specify `'twin.macro'` in our order config, it is not affected. I think if we explicitly specify one, that should override any safety rules.

**Comment by IanVS** [comment]
For reference, there's some additional context around this issue here: https://github.com/IanVS/prettier-plugin-sort-imports/issues/51

@LordZardeck, you bring up an interesting point here.  Whereas it's difficult to accomplish any kind of sorting for generic side-effect-only imports, perhaps we could respect explicit, exact matches like 'twin.macro'.  @LordZardeck, would you mind opening a new issue with a proposal of this idea, so we can discuss it further?
