### ISSUE TITLE
Comments on same line as import are moved down

### ISSUE THREAD

**Issue by IanVS** [IanVS/prettier-plugin-sort-imports#9]
**Your Environment**

-   **Prettier version**: 2.5.1
-   **node version**: 16.13.1

**Describe the bug**

We have the same issue as https://github.com/trivago/prettier-plugin-sort-imports/issues/149, on the latest version 3.3.1.

**To Reproduce**

See issue mentioned above.

**Comment by fbartho** [comment]
I noticed this bug, and also want it fixed

**Comment by fbartho** [comment]
@IanVS what is the correct sort / layout for the following code-snippet?

```ts
import {
     // b: line -1
  b, // b: line  0
     // b: line +1
  a,
} from "irrelevant";
```

Our current code produces:
```ts
import {
    // b: line  0
    // b: line +1
    a, // b: line -1
    b,
} from "irrelevant";
```
Which is obviously bugged 🐛💔.

I think users might expect us to produce:
```diff
import {
+  a,
     // b: line -1
  b, // b: line  0
     // b: line +1
-  a,
} from "irrelevant";
```

There's a couple problems with that expectation though:
## 1. Prettier will strip some of the leading indentation before the comments

At the minimum, it would have to become:
```ts
import {
  a,
  // b: line -1
  b, // b: line  0
  // b: line +1
} from "irrelevant";
```

With significant effort, I could possibly bypass Prettier's indentation-stripping, but this would probably be very difficult.

**❓ Is it okay to let prettier strip alignment whitespace? (If no, we have a fight with Prettier on our hands)**

## 2. Babel's parser likes to attach leading comments preferentially over trailing comments, but there's an ambiguity with comments that are between two import lines.

Where should `// b: line +1` go? Should it be attached to `a,` as a comment before it? or should it be attached to `b` as a trailing comment?

# Proposals
A. Easily: I can strip all comments within/near `ImportSpecifiers` (this would probably be bad, because commenting out imports would then vanish)

B. (With effort) I can probably patch code so that any "on-the-same-line" comments are guaranteed to move with the `ImportSpecifier`

**B.a** (Easily) I can ignore ambiguous specifiers (this will make them move semi-randomly)
**B.b** (With effort) I can choose to associate all other comments with their following import specifier

```ts
import {
  // b: line +1
  a,
  // b: line -1
  b, // b: line  0
} from "irrelevant";
```
Problem: This tears `b: line +1` away and makes it follow `a`'s import specifier.

**B.c** (With effort) I can choose to associate all other comments with their preceding import specifier

```ts
import {
  a,
  // b: line -1
  b, // b: line  0
  // b: line +1
} from "irrelevant";
```

This has the inverse edge case from B.c leading to other lines being torn apart.
<details><summary>🚨 Edge Case</summary>

Slightly different original code:
```ts
import {
     // c: line -1
  c, // c: line  0
     // c: line +1
  b,
  a,
} from "irrelevant";
```
Would become:
```ts
import {
  a,
  // c: line +1
  b,
  // c: line -1
  c, // c: line  0   
} from "irrelevant";
```

</details>

<hr/>
I am attempting proposal `B.a`, and would follow-up with a slight preference for `B.b` if somebody asks me to -- all of these have edge cases though.

I think it's an unresolvable discrepancy around this ambiguity. Any thoughts @IanVS?

**Comment by fbartho** [comment]
## Comments at the Outer Layer

Multi-line comments around the outer-scope of an import:
```ts
/* Leading comment before B */
import B from "b"; /* Trailing comment on same-line as B */
/* Trailing comment on first line after B */


/* Leading comment before A */
import A from "a"; /* Trailing comment on same-line as A */
/* Trailing comment on first line after A */
```

Currently becomes:
```ts
/* Leading comment before B */

/* Trailing comment on same-line as B */

/* Trailing comment on first line after B */

/* Leading comment before A */
import A from "a";
import B from "b";

/* Trailing comment on same-line as A */
/* Trailing comment on first line after A */

```

And for single-line comments:
```ts
// Leading comment before B
import B from "b"; // Trailing comment on same-line as B
// Trailing comment on first line after B


// Leading comment before A
import A from "a"; // Trailing comment on same-line as A
// Trailing comment on first line after A
```

Currently becomes:
```ts
// Leading comment before B
// Trailing comment on same-line as B
// Trailing comment on first line after B
// Leading comment before A
import A from "a";
import B from "b";

// Trailing comment on same-line as A
// Trailing comment on first line after A

```

Generally speaking, my [summary & proposals above](https://github.com/IanVS/prettier-plugin-sort-imports/issues/9#issuecomment-1539169642) apply to these cases as well.

**Comment by IanVS** [comment]
Thanks for digging into this, @fbartho!  

## Comments for import specifiers
I think that we should follow babel's example and give preference to leading comments rather than trailing comments.  This makes the most sense to me logically (why add a comment on a line _after_ an import specifier, anyway?), and sounds like it will be the easiest thing to do.

Further, I would not try to fight prettier's indentation.  That sounds like a losing battle, and I don't think the original comment style is common or desired enough  to be worth it.

So, option `B.b` feels like the ideal to me, but `B.a` is likely fine too.

## Comments for import statements
At a minimum, it seems like we should keep leading comments and same-line comments associated with their import statements, and they should move as a group.  I don't think I really care about trailing comments if they are ambiguous or difficult to deal with, they feel like an uncommon edge case.

**Comment by fbartho** [comment]
It’s pretty common in our codebase to add a same-line comment next to an import-specifier, and that happens similarly next-to an `ImportDeclaration` (if there’s only 1 specifier)
```ts
import {
  Something, // only needed because bar-baz-quux
  DeprecatedThing, // still needed because there is no replacement
} from “lame”;
```

That said, `B.b` is internally consistent with babel’s parser, so I’ll try that, and fallback to `B.a` if I can’t solve it, and I’ll write a blurb for the README about it.

**Comment by IanVS** [comment]
Same-line and leading comments make sense to keep with the import specifier/declaration, if possible.  (Though, I'm not sure if that's exactly what you're proposing).
